import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DisableInputZoom from "@/components/util/disable-input-zoom";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
      </head>
      <body className={inter.className}>
        <DisableInputZoom />
        {children}
      </body>
    </html>
  );
}
